project:
  type: book
  output-dir: docs
  resources:
    - "data/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!clt.qmd"

lang: ko-KR
date-format: "YYYY년 MM월 DD일"

book:
  title: "GPT 통계"
  author: "이광춘"
  date: last-modified
  chapters:
    - index.qmd
    - part: "데이터 관리"
      chapters:
      - data_mgmt.qmd
      - database_mgmt.qmd
      - document.qmd
      - document_auto.qmd
      - model.qmd
      - model_value.qmd

    - part: "사례연구"
      chapters:
        - cs_nightingale.qmd
        - cs_napolean.qmd
        - u_boats.qmd
        - cs_prussia.qmd
        - cs_german_tank.qmd
        - cs_bomber.qmd

    # - part: "출판"
    #   chapters:
        # - clt.qmd
    - references.qmd

filters:
   - lightbox
lightbox: auto

format:
  html:
    theme:
      - cosmo
      - chatGPT4ds.scss
    number-depth: 3
    number-sections: true
    colorlinks: true
    code-overflow: wrap
    code-link: true
    author-meta: "이광춘"
    callout-appearance: simple

  pdf:
    documentclass: "oblivoir"
    classoption: "chapter,a4paper,showtrims,openright,hidelinks"
    pdf-engine: xelatex
    cite-method: biblatex
    keep-tex: true
    number-sections: true
    toc: true

mainfont: "NanumGothic"
sansfont: "NanumGothic"
monofont: "D2Coding"

bibliography: references.bib
csl: biomed-central.csl
link-citations: true


knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: false
editor_options:
  chunk_output_type: console


execute:
  freeze: auto

editor: source
