{
  "hash": "d140f1c1d94488b79c336a49e74dcabe",
  "result": {
    "markdown": "---\noutput: html_document\neditor_options: \n  chunk_output_type: console\n---\n\n\n# 사례 연구\n\n## 교통사고\n\n포아송은 미래에 발생할 경우의 수를 예측하기 위해서 포아송 분포를 창안했다.\n좀더 구체적으로 고정된 시간 범위에 발생할 사건을 예측하기 위해서다.\n\n한가지 사례로 한국 R 사용자회 페이스북 그룹에 \n매주 페이스북 게시글을 올리는데 좋아요를 누르는 평균 회원수가 10명이다.\n새로운 페이스북 게시글을 올렸는데 좋아요를 누른 회원이 15명이 될 확률은 얼마나 될까?\n\n이와 같이 다음주(미래) 좋아요를 누른(사건) 회원수가 15명(5, 10, 20, ...)이 될 \n확률을 알고 싶은 것이다.\n\n### 포아송 분포 수렴\n\n다음 조건을 만족할 때 이항분포가 포아송 분포로 수렴되어 근사할 수 있다.\n\n1. 시행 횟수 $n$ 이 매우 크다.\n2. 성공 확률 $p$ 가 매우 작다.\n3. 따라서, $\\lambda = n \\times p$ 가 일정하다.\n\n이항분포 $Bin(n, p)$는 포아송 분포 $Poi(\\lambda)$에 근사한다.\n\n전체 제품 중에서 고장확률이 매우 작은 전자제품을 사례로 들어보자.\n예를 들어, 어떤 공장에서 10,000개의 제품을 제조했을 때, \n각 제품이 고장날 확률이 0.0001이라고 가정하면 \n이항분포로 전체 제품 중 1개 고장확률을 계산할 수 있지만, \n제품 수가 매우 크고 고장 확률이 매우 작기 때문에 \n$\\lambda = np = 10,000 \\times 0.0001 = 1$를 갖는 \n포아송 분포를 사용하여 근사할 수 있다. \n\n### 월간 교통사고\n\n한 도시의 주요 교차로에서, \n지난 1년 동안의 데이터를 기반으로 하루 평균 3건의 교통 사고가 발생했다고 가정하자. \n이 정보를 바탕으로 특정 날에 교통 사고가 발생할 횟수의 확률 분포를 예측해보자.\n\n포아송 분포의 평균은 $\\lambda$이며, \n이 경우에는 하루 평균 교통 사고 횟수인 3으로 설정할 수 있다.\n\n이제 포아송 분포의 확률 질량 함수를 사용하여, \n특정 날에 교통 사고가 k번 발생할 확률을 계산할 수 있다.\n\n$$\nP(X=k) = \\frac{\\lambda^k e^{-\\lambda}}{k!}\n$$\n\n여기서, $e$는 자연상수입니다.\n\n예를 들어, 특정 날에 교통 사고가 정확히 2번 발생할 확률을 계산하려면:\n\n$$P(X=2) = \\frac{3^2 e^{-3}}{2!} = 0.224$$\n\n한걸음 더 들어가 실세 [교통사고분석시스템(TAAS)](https://taas.koroad.or.kr/) 웹사이트에서 \n2022년 월별 교통사고 데이터를 얻을 수 있다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\naccident_raw <- read_excel(\"data/2022년_월별_교통사고.xlsx\", sheet = \"2022년도 월별 교통사고\", skip = 2)\n\naccident_tbl <- accident_raw |> \n  janitor::clean_names(ascii = FALSE) |> \n  select(월, 사고건수 = 사고건수_건) \n\naccident_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   월    사고건수\n   <chr>    <dbl>\n 1 01월     15894\n 2 02월     12362\n 3 03월     13620\n 4 04월     16472\n 5 05월     18065\n 6 06월     16481\n 7 07월     17115\n 8 08월     16496\n 9 09월     17216\n10 10월     18508\n11 11월     17578\n12 12월     17029\n```\n\n\n:::\n:::\n\n\n월별 평균 사고건수를 `mean()` 함수를 사용해서 계산할 수 있다.\n교통량은 상당히 크고, 교통사고 확률은 매우 낮기 때문에 포아송 분포로 근사를 하는 것이 가능하다.\n교통사고 건수가 많기 때문에 단위를 천대 기준으로 조정하여 포아송 분포 모수 $\\lambda$를 계산한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_mean <- mean(accident_tbl$사고건수) / 1000\n\naccident_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16.403\n```\n\n\n:::\n:::\n\n\n월별로 2만대 이상 교통사고가 발생될 경우 교통사고 환자수가 급증하여 병원에 큰 부하가 걸려\n사회적 문제가 된다는 가정하에 월별로 2만대 이상 교통사고가 발생할 확률을 계산해보자.\n\n\n$P(X \\geq 20)$ 확률값은 전체 경우의 수에서 0 ~ 1.9 만대 사고건수가 발생할 확률을 빼주면\n계산이 가능하고 다음과 같이 수식으로 표현할 수 있다.\n\n$$\nP(X \\geq 20) = 1 - (P(X=0) + P(X=1) + \\ldots + P(X=19))\n$$\n\n이를 R 코드로 작성하면 다음과 같이 함수형 프로그래밍 `purrr` 패키지 `map_dbl()` 함수와 \n포아송 함수에 $\\lambda = 16.403$를 넣어 계산이 가능하거나 내장 함수 `ppois()`로 직접 동일한 계산작업을 수행할 수 있다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\naccident_prob <- 1 - sum(map_dbl(0:19, ~ (accident_mean^.x * exp(-accident_mean)) / factorial(.x)))\n# 1 - ppois(19, lambda = 16.403)\n\naccident_prob\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2169535\n```\n\n\n:::\n:::\n\n\n\n## 프로이센 기병 사망자\n\n프로이센 기병대에서 말 발길질로 사망한 병사의 수를 \n1875년부터 1894년까지, 14개의 기병 군단을 대상으로 수집한 \n데이터([Prussian Horse-Kick Data](https://www.randomservices.org/random/data/HorseKicks.html))가 포아송 분포에 잘 적합되는 것으로 유명하다. \n\n![](images/horse_kicks.jpg)\n\n원본 데이터를 디지털로 복원한 후에 고정된 기간 말 발차기 사망자수를 빈도통계를 통해 표로 정리할 수 있다. 총 관측 횟수는 $14 \\times 20 = 280$ (즉, 1875년부터 1894년까지 20년간 프로이센 군단 14개를 관측), 총 사망자 병사수가 196명으로부터 평균 사망병사수를 $\\lambda = \\frac{196}{280} = 0.7$ 으로 계산할 수 있다. 다음으로 포아송분포에 적합시켜서 분포로부터 말 발차기 사망자수 빈도수를 계산한다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rvest)\nlibrary(gt)\nlibrary(gtExtras)\n\nkick_raw <- read_html(x = 'https://www.randomservices.org/random/data/HorseKicks.html') |> \n  html_node(\"table\") |> \n  html_table()\n\n# kick_raw |> \n#   write_csv(\"data/horse_kick.csv\")\n\nkick_tbl <- kick_raw |> \n  pivot_longer(-Year, names_to = \"군단\", values_to = \"병사수\") |> \n  count(사망횟수 = 병사수, name = \"빈도수\") |> \n  mutate(사망자수 = 사망횟수 * 빈도수)  |> \n  mutate(포아송적합 = map_dbl(사망횟수, dpois, lambda = 196/280) * 280) |> \n  mutate(포아송적합 = round(포아송적합, digits = 0)) |> \n  janitor::adorn_totals(c(\"row\"), name = \"합계\")\n\nkick_tbl |> \n  gt() |> \n  gt_theme_538() |> \n  cols_align(\"center\") |> \n  gt::tab_spanner(label = \"데이터\", \n                  columns = c(사망횟수, 빈도수))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hkqzpokhhs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#hkqzpokhhs table {\n  font-family: Chivo, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hkqzpokhhs thead, #hkqzpokhhs tbody, #hkqzpokhhs tfoot, #hkqzpokhhs tr, #hkqzpokhhs td, #hkqzpokhhs th {\n  border-style: none;\n}\n\n#hkqzpokhhs p {\n  margin: 0;\n  padding: 0;\n}\n\n#hkqzpokhhs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: 300;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: none;\n  border-top-width: 3px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hkqzpokhhs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hkqzpokhhs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hkqzpokhhs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_bottom_border {\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_col_headings {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: normal;\n  text-transform: uppercase;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hkqzpokhhs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: normal;\n  text-transform: uppercase;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hkqzpokhhs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hkqzpokhhs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hkqzpokhhs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hkqzpokhhs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hkqzpokhhs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hkqzpokhhs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #FFFFFF;\n  vertical-align: middle;\n}\n\n#hkqzpokhhs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hkqzpokhhs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hkqzpokhhs .gt_row {\n  padding-top: 3px;\n  padding-bottom: 3px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hkqzpokhhs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-right-style: solid;\n  border-right-width: 0px;\n  border-right-color: #FFFFFF;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hkqzpokhhs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hkqzpokhhs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hkqzpokhhs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hkqzpokhhs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hkqzpokhhs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hkqzpokhhs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hkqzpokhhs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hkqzpokhhs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hkqzpokhhs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hkqzpokhhs .gt_sourcenote {\n  font-size: 12px;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hkqzpokhhs .gt_left {\n  text-align: left;\n}\n\n#hkqzpokhhs .gt_center {\n  text-align: center;\n}\n\n#hkqzpokhhs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hkqzpokhhs .gt_font_normal {\n  font-weight: normal;\n}\n\n#hkqzpokhhs .gt_font_bold {\n  font-weight: bold;\n}\n\n#hkqzpokhhs .gt_font_italic {\n  font-style: italic;\n}\n\n#hkqzpokhhs .gt_super {\n  font-size: 65%;\n}\n\n#hkqzpokhhs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hkqzpokhhs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hkqzpokhhs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hkqzpokhhs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hkqzpokhhs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hkqzpokhhs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hkqzpokhhs .gt_indent_5 {\n  text-indent: 25px;\n}\n\ntbody tr:last-child {\n  border-bottom: 2px solid #ffffff00;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"데이터\">\n        <span class=\"gt_column_spanner\">데이터</span>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"사망자수\">사망자수</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"포아송적합\">포아송적합</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"사망횟수\">사망횟수</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"빈도수\">빈도수</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"사망횟수\" class=\"gt_row gt_center\">0</td>\n<td headers=\"빈도수\" class=\"gt_row gt_center\">144</td>\n<td headers=\"사망자수\" class=\"gt_row gt_center\">0</td>\n<td headers=\"포아송적합\" class=\"gt_row gt_center\">139</td></tr>\n    <tr><td headers=\"사망횟수\" class=\"gt_row gt_center\">1</td>\n<td headers=\"빈도수\" class=\"gt_row gt_center\">91</td>\n<td headers=\"사망자수\" class=\"gt_row gt_center\">91</td>\n<td headers=\"포아송적합\" class=\"gt_row gt_center\">97</td></tr>\n    <tr><td headers=\"사망횟수\" class=\"gt_row gt_center\">2</td>\n<td headers=\"빈도수\" class=\"gt_row gt_center\">32</td>\n<td headers=\"사망자수\" class=\"gt_row gt_center\">64</td>\n<td headers=\"포아송적합\" class=\"gt_row gt_center\">34</td></tr>\n    <tr><td headers=\"사망횟수\" class=\"gt_row gt_center\">3</td>\n<td headers=\"빈도수\" class=\"gt_row gt_center\">11</td>\n<td headers=\"사망자수\" class=\"gt_row gt_center\">33</td>\n<td headers=\"포아송적합\" class=\"gt_row gt_center\">8</td></tr>\n    <tr><td headers=\"사망횟수\" class=\"gt_row gt_center\">4</td>\n<td headers=\"빈도수\" class=\"gt_row gt_center\">2</td>\n<td headers=\"사망자수\" class=\"gt_row gt_center\">8</td>\n<td headers=\"포아송적합\" class=\"gt_row gt_center\">1</td></tr>\n    <tr><td headers=\"사망횟수\" class=\"gt_row gt_center\">합계</td>\n<td headers=\"빈도수\" class=\"gt_row gt_center\">280</td>\n<td headers=\"사망자수\" class=\"gt_row gt_center\">196</td>\n<td headers=\"포아송적합\" class=\"gt_row gt_center\">279</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n시각적으로 실제 관측한 빈도수와 포아송 분포로부터 추정한 값을 함께 겹칠 경우 일부 차이가 있긴 하지만 대체로 포아송 분포에 잘 적합됨을 확인할 수 있다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkick_tbl |> \n  filter(사망횟수 != \"합계\") |> \n  ggplot() +\n    geom_segment(aes(x = 사망횟수, xend = 사망횟수, y = 0, yend=빈도수),\n                 linewidth= 2) +\n    geom_point(aes(사망횟수, 포아송적합), size=3, color=\"red\") +\n    labs(x = \"말 발차기로 사망한 병사 수\",\n         y = \"빈도수\",\n         title = \"말 발길질로 인한 프로이센 병사 사망\",\n         subtitle = \"실제 관측 데이터와 포아송분포 적합 기대값\")\n```\n\n::: {.cell-output-display}\n![](case_study_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n## 런던 투하 V2 로켓  {#v2-rocket}\n\n2차 세계대전 중 독일은 신형 무기 V1, V2 로켓을 개발하여 전쟁 막판에 영국 런던을 폭격하여 반전을 노렸다.\n독일 신형폭탄의 공격을 받은 영국에서는 독일에서 발사한 신형 폭탄이 정밀 타격한 것인지 아니면 무작위로 대충 발사를 한 것인지 데이터를 통해 검정을 하고자 한다. [^clark-poisson] [^v2-bomb-stat]\n\n[^clark-poisson]: [R. D. Clarke, “An Application of the Poisson Distribution,” Journal of the Institute of Actuaries, Vol. 72 (1946), p. 481; V-2]()\n\n[^v2-bomb-stat]: [Generalized Linear Models - 4. Poisson Models for Count Data](http://data.princeton.edu/wws509/notes/c4s1.html)\n\n\n### 데이터 {#v2-data}\n\n가장 먼저 데이터를 준비한다. 데이터는 [R.D. Clarke, \"An Applicatin of the Poisson Distribution\"](https://www.actuaries.org.uk/system/files/documents/pdf/0481.pdf)을 참조한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. 기본 데이터 --------- \n\nbombs <- c(\"0 개\",\"1 개\", \"2 개\",\"3 개\",\"4 개\",\"5 개 이상\")\nhit <- c(229, 211, 93, 35, 7, 1)\nexpected <- c(226.74, 211.39, 98.54, 30.62, 7.14, 1.57)\n\nbomb_df <- tibble(bombs, hit, expected)\nbomb_df |> \n  gt() |> \n  gt_theme_538()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"sutqrrpmfj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#sutqrrpmfj table {\n  font-family: Chivo, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sutqrrpmfj thead, #sutqrrpmfj tbody, #sutqrrpmfj tfoot, #sutqrrpmfj tr, #sutqrrpmfj td, #sutqrrpmfj th {\n  border-style: none;\n}\n\n#sutqrrpmfj p {\n  margin: 0;\n  padding: 0;\n}\n\n#sutqrrpmfj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: 300;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: none;\n  border-top-width: 3px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sutqrrpmfj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sutqrrpmfj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sutqrrpmfj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_bottom_border {\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_col_headings {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: normal;\n  text-transform: uppercase;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sutqrrpmfj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: normal;\n  text-transform: uppercase;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sutqrrpmfj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sutqrrpmfj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sutqrrpmfj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sutqrrpmfj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sutqrrpmfj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sutqrrpmfj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #FFFFFF;\n  vertical-align: middle;\n}\n\n#sutqrrpmfj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sutqrrpmfj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sutqrrpmfj .gt_row {\n  padding-top: 3px;\n  padding-bottom: 3px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sutqrrpmfj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-right-style: solid;\n  border-right-width: 0px;\n  border-right-color: #FFFFFF;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sutqrrpmfj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sutqrrpmfj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sutqrrpmfj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sutqrrpmfj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sutqrrpmfj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sutqrrpmfj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sutqrrpmfj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sutqrrpmfj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sutqrrpmfj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sutqrrpmfj .gt_sourcenote {\n  font-size: 12px;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sutqrrpmfj .gt_left {\n  text-align: left;\n}\n\n#sutqrrpmfj .gt_center {\n  text-align: center;\n}\n\n#sutqrrpmfj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sutqrrpmfj .gt_font_normal {\n  font-weight: normal;\n}\n\n#sutqrrpmfj .gt_font_bold {\n  font-weight: bold;\n}\n\n#sutqrrpmfj .gt_font_italic {\n  font-style: italic;\n}\n\n#sutqrrpmfj .gt_super {\n  font-size: 65%;\n}\n\n#sutqrrpmfj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sutqrrpmfj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sutqrrpmfj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sutqrrpmfj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sutqrrpmfj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sutqrrpmfj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sutqrrpmfj .gt_indent_5 {\n  text-indent: 25px;\n}\n\ntbody tr:last-child {\n  border-bottom: 2px solid #ffffff00;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"bombs\">bombs</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"hit\">hit</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"expected\">expected</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">0 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">229</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">226.74</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">1 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">211</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">211.39</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">2 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">93</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">98.54</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">3 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">35</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">30.62</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">4 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">7</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">7.14</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">5 개 이상</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">1</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">1.57</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### 포아송 분포 {#v2-poisson}\n\n런던에 떨어진 폭탄이 포아송 분포, 즉 무작위로 떨어진 것이라고 가정하고 시각화를 한다.\n포아송 분포는 모수가 $\\lambda$ 하나만 추정하면 되기 때문에 데이터에서 모수를 추정한다.\n\n$$P(\\text{ 해당 구간에서 발생한 k개 사건(k events in interval)}) = e^{-\\lambda}\\frac{\\lambda^k}{k!}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. 포아송 분포 --------- \n\nhit <- 537\narea <- 576\n\n(lambda <- hit/area)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9322917\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(bomb_df, aes(x=bombs,xend=bombs, y=0, yend=hit)) +\n  geom_segment(size=1.5) +\n  geom_point(aes(bombs, expected), size=2, color=\"red\") +\n  labs(x=\"런던 지역에 투하된 폭탄 수\", y=\"런던 지역 숫자\", title=\"영국 런던에 떨어진 V2 로켓 폭탄\",\n       subtitle=\"실제 투하 폭탄수와 포아송 분포로 추정한 폭탄수\")\n```\n\n::: {.cell-output-display}\n![](case_study_files/figure-html/v2-viz-1.png){width=672}\n:::\n:::\n\n\n모수($\\lambda$)는 0.9322917로 추정된다. 이를 실제 데이터와 포아송 분포에서 나온 데이터와 겹쳐 시각화한다. \n\n예를 들어, 폭탄이 투하되지 않을 확률은 다음과 같다.\n\n$$P(x=0) = e^{-0.9322917}\\frac{0.9322917^0}{0!} = 0.3936506$$\n\n이를 R 코드로 표현하면 다음과 같다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda^0 *exp(-lambda) / factorial(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3936506\n```\n\n\n:::\n:::\n\n\n\n### 가설 검정 {#v2-goodness-of-fit}\n\n시각적으로 살펴봤지만, 통계적 가설검정을 통해 다시 한번 런던에 투척된 폭탄이 포아송 분포를 따르는 것인지 검정해본다.\n\n- 귀무가설($H_0$): 런던에 투하된 폭탄은 무작위로 떨어진 것이다. 즉, 폭탄이 떨어진 분포는 포아송 분포다.\n- 대립가설($H_A$): 폭탄이 떨어진 것은 의도를 갖고 특정지역에 투하된 것이다.\n\n유의수준을 설정하고 검정통계량 $\\chi^2$을 정의해서 계산하면 귀무가설을 채택하게 된다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. 통계적 검정 --------- \n\nchisq.test(bomb_df$hit, p=bomb_df$expected, rescale.p=TRUE, simulate.p.value=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities with simulated p-value (based\n\ton 2000 replicates)\n\ndata:  bomb_df$hit\nX-squared = 1.1709, df = NA, p-value = 0.9505\n```\n\n\n:::\n\n```{.r .cell-code}\n# 4. 최종 데이터 ---------\n\nbomb_df$r_expected <- 573 * c( dpois(0:4, lambda), 1 - sum(dpois(0:4, lambda)))\n\nbomb_df |> \n  gt() |> \n    gt_theme_538()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"sukikuyxoa\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#sukikuyxoa table {\n  font-family: Chivo, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sukikuyxoa thead, #sukikuyxoa tbody, #sukikuyxoa tfoot, #sukikuyxoa tr, #sukikuyxoa td, #sukikuyxoa th {\n  border-style: none;\n}\n\n#sukikuyxoa p {\n  margin: 0;\n  padding: 0;\n}\n\n#sukikuyxoa .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: 300;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: none;\n  border-top-width: 3px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sukikuyxoa .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sukikuyxoa .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sukikuyxoa .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_bottom_border {\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_col_headings {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: normal;\n  text-transform: uppercase;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sukikuyxoa .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: normal;\n  text-transform: uppercase;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sukikuyxoa .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sukikuyxoa .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sukikuyxoa .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sukikuyxoa .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sukikuyxoa .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sukikuyxoa .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #FFFFFF;\n  vertical-align: middle;\n}\n\n#sukikuyxoa .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sukikuyxoa .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sukikuyxoa .gt_row {\n  padding-top: 3px;\n  padding-bottom: 3px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sukikuyxoa .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-right-style: solid;\n  border-right-width: 0px;\n  border-right-color: #FFFFFF;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sukikuyxoa .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sukikuyxoa .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sukikuyxoa .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sukikuyxoa .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sukikuyxoa .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sukikuyxoa .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sukikuyxoa .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sukikuyxoa .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sukikuyxoa .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sukikuyxoa .gt_sourcenote {\n  font-size: 12px;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sukikuyxoa .gt_left {\n  text-align: left;\n}\n\n#sukikuyxoa .gt_center {\n  text-align: center;\n}\n\n#sukikuyxoa .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sukikuyxoa .gt_font_normal {\n  font-weight: normal;\n}\n\n#sukikuyxoa .gt_font_bold {\n  font-weight: bold;\n}\n\n#sukikuyxoa .gt_font_italic {\n  font-style: italic;\n}\n\n#sukikuyxoa .gt_super {\n  font-size: 65%;\n}\n\n#sukikuyxoa .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sukikuyxoa .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sukikuyxoa .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sukikuyxoa .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sukikuyxoa .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sukikuyxoa .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sukikuyxoa .gt_indent_5 {\n  text-indent: 25px;\n}\n\ntbody tr:last-child {\n  border-bottom: 2px solid #ffffff00;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"bombs\">bombs</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"hit\">hit</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"expected\">expected</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: black;\" scope=\"col\" id=\"r_expected\">r_expected</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">0 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">229</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">226.74</td>\n<td headers=\"r_expected\" class=\"gt_row gt_right\">225.561771</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">1 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">211</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">211.39</td>\n<td headers=\"r_expected\" class=\"gt_row gt_right\">210.289359</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">2 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">93</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">98.54</td>\n<td headers=\"r_expected\" class=\"gt_row gt_right\">98.025509</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">3 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">35</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">30.62</td>\n<td headers=\"r_expected\" class=\"gt_row gt_right\">30.462788</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">4 개</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">7</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">7.14</td>\n<td headers=\"r_expected\" class=\"gt_row gt_right\">7.100051</td></tr>\n    <tr><td headers=\"bombs\" class=\"gt_row gt_left\">5 개 이상</td>\n<td headers=\"hit\" class=\"gt_row gt_right\">1</td>\n<td headers=\"expected\" class=\"gt_row gt_right\">1.57</td>\n<td headers=\"r_expected\" class=\"gt_row gt_right\">1.560522</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### 지리정보를 통한 이해 {#v2-spatial}\n\n공간정보를 활용한 사례로 이를 공간정보에 시각화하면 다음과 같다.\n물론 정확한 데이터가 없어 런던 남부에 떨어진 폭탄이 포아송 분포를 따른다고 가정하고 576개 구획으로 나눈 것에 임의로 폭탄이 떨어진 것을 시각화하면 다음과 같다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 5. 지리정보 ---------\nlibrary(spatstat)\npar(mar = rep(0, 4))\n\n# 24*24 = 576\nsouth_london <- rpoispp(lambda, win = owin(c(0, 24), c(0, 24)))\nplot(south_london, main=\"\", cex=0.5)\nabline(h = 0:24, v = 0:24, col = \"lightgray\", lty = 3)\n```\n\n::: {.cell-output-display}\n![](case_study_files/figure-html/v2-spatial-viz-1.png){width=672}\n:::\n:::\n\n\n포아송 분포를 가정하고 통계적 검정도 물론 가능하다. `spatstat` 팩키지의 함수를 활용하여 통계적 검정을 해도 동일한 결론에 도달하게 된다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbomb_test <- quadrat.test(south_london, nx = 24, ny = 24, method=\"Chisq\")\nbomb_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test of CSR using quadrat counts\n\ndata:  south_london\nX2 = 591.53, df = 575, p-value = 0.6154\nalternative hypothesis: two.sided\n\nQuadrats: 24 by 24 grid of tiles\nTessellation is marked\n```\n\n\n:::\n:::\n",
    "supporting": [
      "case_study_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}